### ISSUE TITLE
Inspiration Drone enhancement?

### ISSUE THREAD

**Issue by xhadrick** [KomradeSpectre/AetheriumMod#12]
Is it possible to allow the Inspiration Drone to apply to all currently owned drones, not just drones purchased after the item is obtained? It's kind of unfortunate to have a couple drones before finding this item and having to wait for them to die and purchase them again just to get them inspired.

**Comment by KomradeSpectre** [comment]
Feature is coming in the next version, thanks to @cheeeeeeeeeen 's work on the item. It will be able to be enabled via config.

**Comment by xhadrick** [comment]
Awesome! Love the mod, by the way. Super cool items across the board.
