### ISSUE TITLE
Blaster Sword + Shield [Feature request]

### ISSUE THREAD

**Issue by Coffe-e** [KomradeSpectre/AetheriumMod#19]
A possible config option to enable blaster sword's buff w/o full shields?

Not necessary, but would be nice.

**Comment by cheeeeeeeeeen** [comment]
@Coffe-e Define the feature better. Seems vague.

Did you mean a feature where it will still fire swords regardless of shield? Only full health basis?

**Comment by Coffe-e** [comment]
I meant for it to fire w/o the "full shields" requirement. As currently you need full health + shields in order to get blaster sword's buff (that allows you to fire swords).

I felt it'd be nice since shield takes 7 seconds to recharge, but didn't want to have it be default

**Comment by cheeeeeeeeeen** [comment]
I'm not sure... it would be truly OP with Transcendence.

**Comment by KomradeSpectre** [comment]
Just for some clarity. It operates on the combinedhealthfraction system. This means for example if you had 20% health, 60% shields, and 20% barrier, the threshold is met and the swords will fire still.

**Comment by cheeeeeeeeeen** [comment]
I guess the description and pickup lines can get a rework for better clarity.

**Comment by KomradeSpectre** [comment]
I have reworked the description to clarify the condition better. The beginning bit reads:
`When your health bar is greater than or equal to 100% full (from health, shields, barrier, or a combination of any)`
