### ISSUE TITLE
[Change Request] Shark Teeth Nerf and Alien Magnet Nerf

### ISSUE THREAD

**Issue by breadguyyy** [KomradeSpectre/AetheriumMod#25]
**Feature Name**

Shark Teeth
Alien Magnet

**Change Proposal**

Shark Teeth default # of ticks value 10->5

Alien Magnet default starting force 6->3, force per stack 1->2

**Why I Think It Benefits The Mod**

the #1 feedback I see about this mod is that shark teeth is too strong, and I tend to agree. Reducing the number of ticks reduces the incredibly potent synergies with repulsion armor and razorwire without gutting them, and keeping teeth's niche in tact.

alien magnet gets pretty out of hand starting at 6 and doesn't really have a good reason to stack it since it's immediately so powerful

**Comment by KomradeSpectre** [comment]
Good proposal. I think I'll do this one.

**Comment by KomradeSpectre** [comment]
Done. Will be in next version.
