### ISSUE TITLE
[Change Request] Make Accursed Potion Louder

### ISSUE THREAD

**Issue by breadguyyy** [KomradeSpectre/AetheriumMod#26]
**Feature Name**
Accursed Potion

**Change Proposal**
Make activation sound louder

**Why I Think It Benefits The Mod**
better clarity for when youre suddenly under the effects of a serious debuff (or buff for that matter)

**Comment by KomradeSpectre** [comment]
Fair suggestion, will look into doing it.

**Comment by KomradeSpectre** [comment]
I'll actually have to implement a sound for it though. It has no sound by itself as it stands.

**Comment by KomradeSpectre** [comment]
Done.
