### ISSUE TITLE
Item Tier Change Suggestions

### ISSUE THREAD

**Issue by breadguyyy** [KomradeSpectre/AetheriumMod#29]
**Shielding Core:**
Tier: Green -> White
Affect: 15+10 armor per stack while shields active -> 5+5 armor per stack while shields active (still gives 4% shield)
Reason: It's a pretty straight forward effect and feels simple enough to be common tier, feels too weak as a green to me and makes shield synergy feel too sparse due to how large the green item pool is along with their higher rarity.

**Inspiring Drone**
Tier: Red -> Green
Affect: Gain 50%+50% of owners stats per stack. -> Gain 10%+10% of owners stats per stack. (may need to adjust teleport times and distance for balance as well)
Reason: Similarly as above, being in the red tier make drone synergy feel too sparse and run defining when picked up, imo. I think it fits better in the green tier with a lower power level. IDK I don't really have a super descript way to sell this one, it just feels right. (disclaimer: I am biased because I want to use it more.)

**Comment by KomradeSpectre** [comment]
I can implement a config for the second one, but as you suggested yourself in the discord, I will keep the shielding core at green albeit with a small buff.
