### ISSUE TITLE
Configs arent created since last update.

### ISSUE THREAD

**Issue by fwenny** [KomradeSpectre/AetheriumMod#3]
Im not sure if I misunderstood the last patch, but I see no configs being created.
I see no errors in the output log.

**Comment by KomradeSpectre** [comment]
Are you on version 0.2.0?

**Comment by fwenny** [comment]
Hiya, yeah. Im on 0.2.0, which is the latest in the thunderstore.

**Comment by fwenny** [comment]
I created a new profile with only Aetherium installed, no configs are installed, so its not mod related.

**Comment by fwenny** [comment]
After further checking, it seems the mod isnt being loaded at all. As before its the only one installed.

**Comment by KomradeSpectre** [comment]
Perhaps an issue regarding mod loading code? I haven't received any reports of this from any other player, and I cannot replicate it. Any advice on replicating it?

**Comment by fwenny** [comment]
Im using r2modman. I opened a new profile, and only installed this mod, and it doesnt work.

**Comment by KomradeSpectre** [comment]
Do you have the required TILER2, R2API, and BepinEX dependencies alongside it?

**Comment by fwenny** [comment]
Yes. It auto installs everything you need, since it reads things directly
from the Thunderstore.

**Comment by fwenny** [comment]
Well, whether youve found the issue and fixed it, or by blind luck, the last patch you released fixed the issue and configs are being generated again.

Regardless, thank you.
