### ISSUE TITLE
Blaster Sword deals double the configured damage

### ISSUE THREAD

**Issue by MightyW0lf** [KomradeSpectre/AetheriumMod#30]
[In this clip](https://youtu.be/bnBu9fcDYMc), the explosion deals 70 damage (+12 from the DoT). Acrid's M1 deals 35 (200%) damage. The explosion should deal 200% as well (according to the configuration and the item's detailed description). Lowering the damage multiplier in the configuration to `1` causes the explosion to deal 200% damage.

Also side note: The detailed description doesn't mention the crippling debuff and none of the item's descriptions mention the DoT from the impaled sword.

Mods:
* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* **KomradeSpectre-Aetherium-0.4.7**
* Harb-DebugToolkit-3.4.2

**Comment by KomradeSpectre** [comment]
Thanks for the report. I'll look into this as I'm working on a visual change for the item as well.

**Comment by KomradeSpectre** [comment]
Solved. There was a field on ImpactExplosion that I did not see when creating the projectile for "BlastDamageCoefficient" which was set to 2. I have set this to 1 now. We're all good now!
