### ISSUE TITLE
Void Heart leaves expired Dio's in inventory on successful revive

### ISSUE THREAD

**Issue by gaforb** [KomradeSpectre/AetheriumMod#31]
Tested with only Aetherium and it's dependencies, plus debugtoolkit

**Comment by KomradeSpectre** [comment]
I can find a way to solve this, but probably not in time for the 0.5.0 release. That said, I'll leave this open till I find a fix.

**Comment by KomradeSpectre** [comment]
Fixed for next version (0.5.3)
