### ISSUE TITLE
Config wording issue

### ISSUE THREAD

**Issue by sanity-dance** [KomradeSpectre/AetheriumMod#32]
![image](https://user-images.githubusercontent.com/58183513/105567324-1b964b00-5ce6-11eb-8060-877bb03ab6b8.png)

"Blacklist item from AI use?" and "Is the AI allowed to use this item?" are opposite questions. If I say "yes, I want to blacklist this item from AI use", that answer means "no, the AI should not be allowed to use this item."

I'm assuming the blacklist question is what the configuration is trying to ask, since that's how the other item mod configs work. But it could stand some clarification.

**Comment by KomradeSpectre** [comment]
Good catch. Will fix this now. Thanks for the report!
