### ISSUE TITLE
[Config Request] Allow Blaster Sword to work of Total damage, instead of Base

### ISSUE THREAD

**Issue by gaforb** [KomradeSpectre/AetheriumMod#35]
See above - MUL-T Nailgun is scarily good compared to something like Huntress Strafe, would be nice to have the option to level the field a bit.
Additionally if it isn't too difficult, could scale the projectile based on it's damage (BEEG rebar sword)

**Comment by KomradeSpectre** [comment]
This works already off of total damage. 
Take a look
![Image of Blaster Sword projectile code](https://i.imgur.com/JHS7O61.png)

Elaborate if you could what you mean on the first bit. I don't have the drive, or insanity to do the second part.
