### ISSUE TITLE
Witches Ring's "Global Cooldown On Use" config option doesn't work

### ISSUE THREAD

**Issue by MightyW0lf** [KomradeSpectre/AetheriumMod#39]
When `Global Cooldown On Use` is set to `true`, the cooldown effect doesn't do anything on player.

[Demonstration video](https://youtu.be/MUrrJ5OQXWw)
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/6164445/LogOutput.log)

Mods installed:

- bbepis-BepInExPack-5.3.1
- tristanmcpherson-R2API-2.5.14
- **KomradeSpectre-Aetherium-0.5.1**
- Harb-DebugToolkit-3.4.2
- XoXFaby-BetterUI-1.6.17
    - _Bug occurs even without BetterUI, used for demo video to show the effect timer resets._

**Comment by KomradeSpectre** [comment]
I'm an idiot, I only ever checked for the immunity on the victim ever.
![immunity](https://i.imgur.com/0MX4hjY.png)

This will be fixed in the new version. Thanks for the report.
