### ISSUE TITLE
Huge items

### ISSUE THREAD

**Issue by Fornax42** [KomradeSpectre/AetheriumMod#40]
I was playing a multiplayer game just now, and we noticed some items were displayed as very huge (as in 'blocking half the screen when it's in front of you' big)

The items in question were:
Feathered Plume
Shark Teeth
Shielding Core
Jar of Reshaping (couldn't active this item as well)

It didn't happen with other items (like the Blood Soaked Shield I also had)

I was playing a modded character myself, as was my friend here, but another friend who played engineer (but left before taking the screenshot), also had this same problem with the Jar of Reshaping.

I don't have a crash log or error line, since the game ran normally in all other aspects.

(the image only shows the Shielding Core, but the other items were found later in the same run)
![image](https://user-images.githubusercontent.com/18664575/115160517-e442fa80-a098-11eb-8ce8-87941729b112.png)

**Comment by DaedalusGame** [comment]
This is a Starstorm issue.

**Comment by KomradeSpectre** [comment]
This is a starstorm 2 issue, Enforcer issue, and the issue of any mod with modded characters that implement item display rules for my items. I can't implement them for modded characters, the system is opt in. If you see a giant display, bring the issue to that team.
