### ISSUE TITLE
Latest update 0.5.6

### ISSUE THREAD

**Issue by adelthesuper** [KomradeSpectre/AetheriumMod#41]
Your 0.5.6 update just broke the game lol. Risk won't even load now.

**Comment by KomradeSpectre** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/12734451/118750616-c13d6f00-b82d-11eb-987e-8682570956b2.png)

**Comment by KomradeSpectre** [comment]
This is definitively a Starstorm 2 issue, I've fixed any errors that my release DID have on my side this morning, but the error you're talking about persists as a result of their fuckup. Please report it to their team on their discord if you could, enough fire under their asses and they'll fix it maybe.

Thanks for the report though.
