### ISSUE TITLE
Duplicated Gunner Turrets occupy the same space

### ISSUE THREAD

**Issue by gaforb** [KomradeSpectre/AetheriumMod#44]
Engineers Toolbelt spawns duplicate Gunner Turrets in the exact location of the original, which looks a bit odd. This is remedied when they teleport or you move to next stage so not a major issue, but would be a nice upgrade if they spawned just a bit away from the original purchase.

**Comment by KomradeSpectre** [comment]
It's known, I was not ready to release Aetherium in the state that it was, but I was getting sick of getting the huge item display report, and it has since solved it. My DMs are basically quiet now.

**Comment by KomradeSpectre** [comment]
Fixed
