### ISSUE TITLE
6.3 update broke ProperSave 

### ISSUE THREAD

**Issue by gabe-over** [KomradeSpectre/AetheriumMod#49]
Hey, I know it's not your problem, but I noticed after the last update ProperSave Mod stoped working, still saves progress but pressing the Load button does nothing but freeze the character select menu.

**Comment by KomradeSpectre** [comment]
Post a log if you have one related to this, if it's on my side I can fix it with a patch version, if it's on ProperSave's side I can send it on to them.

**Comment by gabe-over** [comment]
weird, updated to 6.3 again, but this time everything works.

**Comment by KomradeSpectre** [comment]
Glad to hear everything works. I'll go ahead and close this.
