### ISSUE TITLE
Accursed Potion [List of found bugs]

### ISSUE THREAD

**Issue by Coffe-e** [KomradeSpectre/AetheriumMod#5]
Certain inaccessible buffs/debuffs are being chosen
[EX: EngiShield, and one with a ! icon.]

Buffs/Debuffs from other mods are being chosen.
[Arti-Extended Ice shield, Enforcer shield movement debuff, etc]

If any of these aren't bugs, my bad.

**Comment by KomradeSpectre** [comment]
Not bugs, with how it is designed, the potion will pull from the available buffs/debuffs defined in the BuffCatalog, with some exclusions (like hidden invincibility, and immune).

**Comment by KomradeSpectre** [comment]
Thanks for the report though as a just in case measure, they're appreciated regardless.
