### ISSUE TITLE
Jade elephant brazer giving buff 61 times

### ISSUE THREAD

**Issue by AimlessRex** [KomradeSpectre/AetheriumMod#51]
Jade elephant brazer gives buff 61 times leaving me with 12020 armor 99% damage resistance

[https://imgur.com/d42OGSj](url)

**Comment by KomradeSpectre** [comment]
![image](https://user-images.githubusercontent.com/12734451/143619203-3b9fceda-3592-4462-97fe-eee98c7b7fd4.png)

Do you have a log that goes along with the screenshot? It may be that you have a mod that alters the stacking mechanics of vanilla buffs.

**Comment by AimlessRex** [comment]
i do not sorry how do i get a log for it?

**Comment by KomradeSpectre** [comment]
It would be in the bepinex folder of your mod installation instance. If you're using R2modman, when you're in one of your profiles, hit `Settings -> All -> Browse Profile Folder`, then open the `BepinEx` folder, and the log will be called `LogOutput.log`. This log will get recreated every time you launch the game.

**Comment by AimlessRex** [comment]
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/7611016/LogOutput.log)

**Comment by KomradeSpectre** [comment]
Do you have a profile code, which you can obtain via `Settings -> Profile -> Export profile as a code` so I can see if there is any mod in your listing that may be modifying vanilla buffs? By default, ElephantArmorBoost is a non-stackable buffdef, so something must be changing it.

Additionally, Cloudburst was having a normal one in your log there, if you'd like I'll toss that at the cloudburst team to see if they can fix their error.

**Comment by AimlessRex** [comment]
yc4wio0eXv

yes please and thanks

**Comment by KomradeSpectre** [comment]
I no longer use the default buff catalog buffs, so this is no longer an issue for me.
