### ISSUE TITLE
Shark Teeth Icon Missing

### ISSUE THREAD

**Issue by Lordician** [KomradeSpectre/AetheriumMod#53]
While doing a singleplayer run with Enforcer with the machine gun primary I found an issue with the Shark Teeth item.
I picked up the Shark Teeth item and right away noticed that in the pick-up notification at the bottom it displayed one of the skill icons of a completely different character (one that was not even present in the run).
Then I noticed that just like Spearof in the Discord the icon of Shark Teeth in my item list was a white square.
The rest of the items all worked fine, I picked up a couple of other Aetherium and modded items without any problems, so it seems pretty exclusive to Shark Teeth right now.

As a reference for how it looked in my item list, i'd like to refer to Spearof's Discord post: https://discord.com/channels/374891192678219777/793925964845023264/914273792346431573

As for my log, I will attach it to this issue.
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/7642909/LogOutput.log)
I picked up the item at line 2700, right after you can see an index out of bounds exception for the Body XML.

**Comment by KomradeSpectre** [comment]
Related to a redundant config option that used an icon for the old shark teeth model, it was set to unused (so not compiled into the bundle) in 0.6.6, so the error comes from the config option to "Use New Icons" being defaulted to true.
