### ISSUE TITLE
[Suggestion] Artifact of the Tyrant Blocklist

### ISSUE THREAD

**Issue by Pyredrid** [KomradeSpectre/AetheriumMod#54]
During the stage where Mithrix steals all the player's items, they can also get the Overload elite type.  Some friends of mine and I found this ramped up the difficulty curve way too much, since damaging shields don't cause items to be given back.

If there was a config option to stop Mithrix from getting certain elite types (maybe even during certain phases), it'd help balancing modpacks including ours.

**Comment by KomradeSpectre** [comment]
I mean yeah sure, I can add this in real quick.

**Comment by KomradeSpectre** [comment]
Done

**Comment by Pyredrid** [comment]
Dude, that was fast.  Thanks!
