### ISSUE TITLE
Randomly dying as stage starts with heart of the void 

### ISSUE THREAD

**Issue by jsundita** [KomradeSpectre/AetheriumMod#58]
This happened in a multiplayer run as paladin.

When my friends and I spawn on a stage, the void heart effect activates. It feels that there is a 50/50 chance of me just straight up dying or living normally. If my friends fail the stage, we don't  go to the results screen but instead watch my non-existent  body in space. This has happened multiple  times when having the item.

**Comment by KomradeSpectre** [comment]
Fixed indev. On body start, you get a few seconds of prevention to the timebomb effect, on max health change you get a few seconds of prevention, etc. This should prevent it from killing you in this way now.
