### ISSUE TITLE
Shielding Core Ineffective.

### ISSUE THREAD

**Issue by Lavoroxan** [KomradeSpectre/AetheriumMod#64]
According to BetterUI by XoXFaby, Shielding Core supposedly does not increase armor at all.

**Comment by Coffe-e** [comment]
I believe the issue may stem from more than a single mod causing this bug, as spikestrip alone doesn't prevent the armor from appearing, but spikestrip in the presence of some other mods does.
[Spikestrip+Mods Log]
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/10115349/LogOutput.log)

[W/O Spikestrip Log]
[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/10115392/LogOutput.log)

**Comment by Coffe-e** [comment]
Note: After reporting this bug to the Spikestrip 2.0 Devs as well, the issue has been found: The Spikestrip item Noops Wool uses the same armor-adding value as Shielding Core, but **_sets_** the armor value instead, causing this incompatibility. A fix is slated for the next Spikestrip update.

**Comment by KomradeSpectre** [comment]
Understood, closing as it should be fixed given that was a year ago. If it pops up again, let me know.
