### ISSUE TITLE
Errors while playing ShigarakiMod

### ISSUE THREAD

**Issue by Jeserkon** [KomradeSpectre/AetheriumMod#65]
When you play a normal game with ShigarakiMod 1.3.0 and Aetherium 0.6.8 installed playing as Shigaraki, an error pops up and repeats itself
This is the error:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Aetherium.Items.ShieldingCore.ShieldedCoreValidator (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_003B)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?-1801424896 (RoR2.CharacterBody ) (at <947c424a953e4014b9eac605ee1cf3cc>:IL_0014)
DMD<>?914734080.Trampoline<RoR2.CharacterBody::FixedUpdate>?824859648 (RoR2.CharacterBody ) (at <d361ad719e524fe49aca09df408b7c3d>:IL_0020)
Aetherium.Items.UnstableDesign.SummonLunarChimera (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_02BB)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?2010620800 (RoR2.CharacterBody ) (at <8f26af16baa1477ba74e969faa73e0f5>:IL_0014)
DMD<>?914734080.Trampoline<RoR2.CharacterBody::FixedUpdate>?-1633061888 (RoR2.CharacterBody ) (at <6a44b3bbe5c648ab8f1882c0177c0dc4>:IL_0020)
Aetherium.Items.Voidheart.VoidheartOverlayManager (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_00EB)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?-680995072 (RoR2.CharacterBody ) (at <4249f47f538d4a63b651dede0b93fcae>:IL_0014)
DMD<>?914734080.Trampoline<RoR2.CharacterBody::FixedUpdate>?420469760 (RoR2.CharacterBody ) (at <7377dede07f14888a100f8c4d5e78409>:IL_0020)
Aetherium.Items.WeightedAnklet.ManageLimiterBuff (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_0001)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?1720418176 (RoR2.CharacterBody ) (at <cd7e934539894f97a6b134fd50e5615e>:IL_0014)
DMD<>?914734080.Trampoline<RoR2.CharacterBody::FixedUpdate>?-1495690240 (RoR2.CharacterBody ) (at <5c5879612f6349c28b43ffd15aca4176>:IL_0020)
Aetherium.Equipment.JarOfReshaping.AddTrackerToBodies (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_0058)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?1683091456 (RoR2.CharacterBody ) (at <8598de56463c407ca6ad577facb2b2ee>:IL_0014)
DMD<>?914734080.Trampoline<RoR2.CharacterBody::FixedUpdate>?-538462208 (RoR2.CharacterBody ) (at <1da85c8b011b4f179c8ac3be0d5e12ba>:IL_0020)
Aetherium.Equipment.EliteEquipment.EliteEquipmentBase.OverlayManager (On.RoR2.CharacterBody+orig_FixedUpdate orig, RoR2.CharacterBody self) (at <728952a0940e4aa1bdfe0581dcbe74d0>:IL_00DF)
DMD<>?914734080.Hook<RoR2.CharacterBody::FixedUpdate>?-742992128 (RoR2.CharacterBody ) (at <a4eba998cccf4e458d1ff33712a3d052>:IL_0014)

It only happens with Aetherium installed

[LogOutput.log](https://github.com/KomradeSpectre/AetheriumMod/files/9841296/LogOutput.log)

**Comment by KomradeSpectre** [comment]
I did notice this one recently while playing as Shirigaki, and will do a brief investigation later on to see if I can figure out why its doing it.

**Comment by KomradeSpectre** [comment]
As far as I can tell, I've fixed this indev by just sanity checking this method even more. Apparently it happened because somehow shigaraki had no character body at some point, or had no health component?
