### ISSUE TITLE
Void Heart + Planula instantly crashes the game when under health threshold.

### ISSUE THREAD

**Issue by PhillipSF** [KomradeSpectre/AetheriumMod#67]
Void Heart when active turns all healing into damage, Planula heals whenever you take damage, but because all healing is taken as damage, Planula procs an insane amount of times at once, crashing the game.

**Comment by KomradeSpectre** [comment]
Fixed indev. I just bypass planula's ability to heal from Void Heart inflicted damage now via a custom Void Heart damage type.
