### ISSUE TITLE
When nullifiers encounter braizer debuffs on tele-radius, game becomes a slide show.

### ISSUE THREAD

**Issue by Darkmega18** [KomradeSpectre/AetheriumMod#68]
https://github.com/JoshTClark/Thalassophobia/issues/7
and cross post of this issue so you two can work out who's more broke.

but basically, your debuff on enemies is being applied constantly. the thallassophobia nullifiers are constantly purging themselves. Game overloads itself seemingly.
it's only worse in my game due to the teleporter radius becoming the whole map once the boss enemies are defeated. and so if any nullifier exists elsewhere in the world, my game essentially becomes a laggy slideshow. :V

**Comment by KomradeSpectre** [comment]
Will investigate this if it's still an issue tonight

**Comment by KomradeSpectre** [comment]
After review, this is on thalassophobia's side related to how the debuffs are being purged. I have left a comment on the open issue for that mod of a better implementation that should solve the issue but it's up to them to implement it.

**Comment by Darkmega18** [comment]
Roger-roger. Thank you.
