### ISSUE TITLE
Inspiring Drone + "The Back-up" [Feature Request]

### ISSUE THREAD

**Issue by Coffe-e** [KomradeSpectre/AetheriumMod#7]
I feel like inspiring drone should work with The Back-up.
Not necessary, but would be nice.

**Comment by KomradeSpectre** [comment]
Will look into doing this if it is reasonable.

**Comment by cheeeeeeeeeen** [comment]
This should be supported now.
![Inspired BackUp](https://i.imgur.com/gE8vnYU.png)

@KomradeSpectre Requesting to close this.
