### ISSUE TITLE
ItemStatsMod Compat

### ISSUE THREAD

**Issue by cheeeeeeeeeen** [KomradeSpectre/AetheriumMod#9]
Add compatibility for ItemStatsMod. It's a good mod for displaying the current stats of the item upon hovering, and displays the next stats if ever you acquire another one of the same item.

Here is the mod: https://thunderstore.io/package/ontrigger/ItemStatsMod/

You can check out my mods on how this was implemented.

**Comment by KomradeSpectre** [comment]
Done.
